/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "file_transfer.h"

bool_t
xdr_file_data (XDR *xdrs, file_data *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->filename, MAXNAME))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->data.data_val, (u_int *) &objp->data.data_len, ~0))
		 return FALSE;
	return TRUE;
}
