/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _FILE_TRANSFER_H_RPCGEN
#define _FILE_TRANSFER_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXNAME 255

struct file_data {
	char *filename;
	struct {
		u_int data_len;
		char *data_val;
	} data;
};
typedef struct file_data file_data;

#define FILETRANSFER 0x31230000
#define FILETRANSFER_V1 1

#if defined(__STDC__) || defined(__cplusplus)
#define DOWNLOAD_FILE 1
extern  file_data * download_file_1(char **, CLIENT *);
extern  file_data * download_file_1_svc(char **, struct svc_req *);
extern int filetransfer_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define DOWNLOAD_FILE 1
extern  file_data * download_file_1();
extern  file_data * download_file_1_svc();
extern int filetransfer_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_file_data (XDR *, file_data*);

#else /* K&R C */
extern bool_t xdr_file_data ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_FILE_TRANSFER_H_RPCGEN */
